export const navigationList = [
  {
    title: "Home",
    url: "/home",
  },
  {
    title: "Movies",
    url: "/movies",
  },
  {
    title: "TV Series",
    url: "tv-series",
  },
  {
    title: "Wishlist",
    url: "wishlist",
  },
  {
    title: "Favorite",
    url: "favorite",
  },
];
export const aksiPopuler = [
  "The Avengers",
  "John Wick",
  "Mad Max: Fury Road",
  "Mission: Impossible - Fallout",
  "Black Panther",
  "Wonder Woman",
  "Guardians of the Galaxy",
  "Fast & Furious 7",
  "The Dark Knight",
  "Die Hard",
  "Inception",
  "Thor: Ragnarok",
  "Logan",
  "Jurassic World",
  "The Matrix",
  "Avatar",
  "Captain America: The Winter Soldier",
  "The Fast and the Furious",
  "Kill Bill",
  "Taken",
  "Edge of Tomorrow",
  "The Equalizer",
  "Kingsman: The Secret Service",
  "Atomic Blonde",
  "Baby Driver",
  "John Wick: Chapter 2",
  "Black Widow",
  "Spider-Man: No Way Home",
  "Furious 9",
  "The Suicide Squad",
];

export const komediPopuler = [
  "Deadpool",
  "The Hangover",
  "Superbad",
  "Anchorman: The Legend of Ron Burgundy",
  "Bridesmaids",
  "Dumb and Dumber",
  "Step Brothers",
  "Pitch Perfect",
  "Napoleon Dynamite",
  "Wedding Crashers",
  "Knocked Up",
  "Mean Girls",
  "The Grand Budapest Hotel",
  "Zoolander",
  "Ferris Bueller's Day Off",
  "The 40-Year-Old Virgin",
  "This Is the End",
  "Neighbors",
  "Ted",
  "Shaun of the Dead",
  "The Wolf of Wall Street",
  "The Nice Guys",
  "Crazy Rich Asians",
  "Toy Story",
  "The Big Lebowski",
  "Tropic Thunder",
  "Pineapple Express",
  "Jumanji: Welcome to the Jungle",
  "Deadpool 2",
  "Jojo Rabbit",
];

export const ListMoviesActions = [
  {
    adult: false,
    backdrop_path: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    genre_ids: [878, 28, 12],
    id: 24428,
    original_language: "en",
    original_title: "The Avengers",
    overview:
      "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
    popularity: 104.593,
    poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    release_date: "2012-04-25",
    title: "The Avengers",
    video: false,
    vote_average: 7.71,
    vote_count: 28965,
  },
  {
    adult: false,
    backdrop_path: "/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 678.807,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 7.826,
    vote_count: 4104,
  },
  {
    adult: false,
    backdrop_path: "/8yACFuo4OaIiKr9hHFlmPcGalKx.jpg",
    genre_ids: [28, 12, 878],
    id: 76341,
    original_language: "en",
    original_title: "Mad Max: Fury Road",
    overview:
      "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
    popularity: 55.397,
    poster_path: "/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    release_date: "2015-05-13",
    title: "Mad Max: Fury Road",
    video: false,
    vote_average: 7.579,
    vote_count: 20760,
  },
  {
    adult: false,
    backdrop_path: "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg",
    genre_ids: [28, 12],
    id: 353081,
    original_language: "en",
    original_title: "Mission: Impossible - Fallout",
    overview:
      "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
    popularity: 70.53,
    poster_path: "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    release_date: "2018-07-13",
    title: "Mission: Impossible - Fallout",
    video: false,
    vote_average: 7.414,
    vote_count: 7427,
  },
  {
    adult: false,
    backdrop_path: "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
    genre_ids: [28, 12, 878],
    id: 284054,
    original_language: "en",
    original_title: "Black Panther",
    overview:
      "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
    popularity: 59.109,
    poster_path: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    release_date: "2018-02-13",
    title: "Black Panther",
    video: false,
    vote_average: 7.392,
    vote_count: 20900,
  },
  {
    adult: false,
    backdrop_path: "/AaABt75ZzfMGrscUR2seabz4PEX.jpg",
    genre_ids: [28, 12, 14],
    id: 297762,
    original_language: "en",
    original_title: "Wonder Woman",
    overview:
      "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
    popularity: 69.824,
    poster_path: "/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
    release_date: "2017-05-30",
    title: "Wonder Woman",
    video: false,
    vote_average: 7.2,
    vote_count: 18833,
  },
  {
    adult: false,
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    genre_ids: [878, 12, 28],
    id: 447365,
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    overview:
      "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    popularity: 1070.71,
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    release_date: "2023-05-03",
    title: "Guardians of the Galaxy Vol. 3",
    video: false,
    vote_average: 8.071,
    vote_count: 4148,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 1203.415,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.314,
    vote_count: 3254,
  },
  {
    adult: false,
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 111.844,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-14",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.511,
    vote_count: 30281,
  },
  {
    adult: false,
    backdrop_path: "/yw55hiqnDOwZiXpkraXu114rmGz.jpg",
    genre_ids: [28, 53],
    id: 562,
    original_language: "en",
    original_title: "Die Hard",
    overview:
      "NYPD cop John McClane's plan to reconcile with his estranged wife is thrown for a serious loop when, minutes after he arrives at her office, the entire building is overtaken by a group of terrorists. With little help from the LAPD, wisecracking McClane sets out to single-handedly rescue the hostages and bring the bad guys down.",
    popularity: 56.792,
    poster_path: "/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg",
    release_date: "1988-07-15",
    title: "Die Hard",
    video: false,
    vote_average: 7.771,
    vote_count: 10088,
  },
  {
    adult: false,
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    genre_ids: [28, 878, 12],
    id: 27205,
    original_language: "en",
    original_title: "Inception",
    overview:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    popularity: 88.56,
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    release_date: "2010-07-15",
    title: "Inception",
    video: false,
    vote_average: 8.4,
    vote_count: 34213,
  },
  {
    adult: false,
    backdrop_path: "/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg",
    genre_ids: [28, 12, 878],
    id: 284053,
    original_language: "en",
    original_title: "Thor: Ragnarok",
    overview:
      "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
    popularity: 79.01,
    poster_path: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    release_date: "2017-10-02",
    title: "Thor: Ragnarok",
    video: false,
    vote_average: 7.596,
    vote_count: 19377,
  },
  {
    adult: false,
    backdrop_path: "/9X7YweCJw3q8Mcf6GadxReFEksM.jpg",
    genre_ids: [28, 18, 878],
    id: 263115,
    original_language: "en",
    original_title: "Logan",
    overview:
      "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
    popularity: 54.011,
    poster_path: "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
    release_date: "2017-02-28",
    title: "Logan",
    video: false,
    vote_average: 7.818,
    vote_count: 17982,
  },
  {
    adult: false,
    backdrop_path: "/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg",
    genre_ids: [28, 12, 878, 53],
    id: 135397,
    original_language: "en",
    original_title: "Jurassic World",
    overview:
      "Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
    popularity: 77.548,
    poster_path: "/A0LZHXUzo5C60Oahvt7VxvwuzHw.jpg",
    release_date: "2015-06-12",
    title: "Jurassic World",
    video: false,
    vote_average: 6.682,
    vote_count: 19281,
  },
  {
    adult: false,
    backdrop_path: "/oMsxZEvz9a708d49b6UdZK1KAo5.jpg",
    genre_ids: [28, 878],
    id: 603,
    original_language: "en",
    original_title: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    popularity: 72.461,
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: "1999-03-30",
    title: "The Matrix",
    video: false,
    vote_average: 8.206,
    vote_count: 23598,
  },
  {
    adult: false,
    backdrop_path: "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: "en",
    original_title: "Avatar",
    overview:
      "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    popularity: 119.034,
    poster_path: "/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    release_date: "2009-12-15",
    title: "Avatar",
    video: false,
    vote_average: 7.6,
    vote_count: 29581,
  },
  {
    adult: false,
    backdrop_path: "/1RWLMyC9KcFfcaoViMiJGSSZzzr.jpg",
    genre_ids: [28, 12, 878],
    id: 100402,
    original_language: "en",
    original_title: "Captain America: The Winter Soldier",
    overview:
      "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
    popularity: 33.336,
    poster_path: "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    release_date: "2014-03-20",
    title: "Captain America: The Winter Soldier",
    video: false,
    vote_average: 7.7,
    vote_count: 17552,
  },
  {
    adult: false,
    backdrop_path: "/jY9ef5nqY4xIIMu3yzW3qamUCoi.jpg",
    genre_ids: [28, 80, 53],
    id: 9799,
    original_language: "en",
    original_title: "The Fast and the Furious",
    overview:
      "Dominic Toretto is a Los Angeles street racer suspected of masterminding a series of big-rig hijackings. When undercover cop Brian O'Conner infiltrates Toretto's iconoclastic crew, he falls for Toretto's sister and must choose a side: the gang or the LAPD.",
    popularity: 5.706,
    poster_path: "/gqY0ITBgT7A82poL9jv851qdnIb.jpg",
    release_date: "2001-06-22",
    title: "The Fast and the Furious",
    video: false,
    vote_average: 6.961,
    vote_count: 9100,
  },
  {
    adult: false,
    backdrop_path: "/k9Ps0EsrTnqbQ4oTTWx628BQ2TW.jpg",
    genre_ids: [28, 80],
    id: 24,
    original_language: "en",
    original_title: "Kill Bill: Vol. 1",
    overview:
      "An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.",
    popularity: 42.784,
    poster_path: "/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    release_date: "2003-10-10",
    title: "Kill Bill: Vol. 1",
    video: false,
    vote_average: 7.97,
    vote_count: 16030,
  },
  {
    adult: false,
    backdrop_path: "/9iQWsXwjOMGDvTDdvCnpiyR0UG3.jpg",
    genre_ids: [28, 53],
    id: 8681,
    original_language: "en",
    original_title: "Taken",
    overview:
      "While vacationing with a friend in Paris, an American girl is kidnapped by a gang of human traffickers intent on selling her into forced prostitution. Working against the clock, her ex-spy father must pull out all the stops to save her. But with his best years possibly behind him, the job may be more than he can handle.",
    popularity: 54.811,
    poster_path: "/y5Va1WXDX6nZElVirPrGxf6w99B.jpg",
    release_date: "2008-02-18",
    title: "Taken",
    video: false,
    vote_average: 7.386,
    vote_count: 10316,
  },
  {
    adult: false,
    backdrop_path: "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
    genre_ids: [28, 878],
    id: 137113,
    original_language: "en",
    original_title: "Edge of Tomorrow",
    overview:
      "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
    popularity: 43.754,
    poster_path: "/xjw5trHV7Mwo61P0kCTy8paEkgO.jpg",
    release_date: "2014-05-27",
    title: "Edge of Tomorrow",
    video: false,
    vote_average: 7.604,
    vote_count: 12706,
  },
  {
    adult: false,
    backdrop_path: "/wHytVsfAZsVDAcABd6iQGmE2j29.jpg",
    genre_ids: [53, 28, 80],
    id: 156022,
    original_language: "en",
    original_title: "The Equalizer",
    overview:
      "McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.",
    popularity: 89.423,
    poster_path: "/9u4yW7yPA0BQ2pv9XwiNzItwvp8.jpg",
    release_date: "2014-09-24",
    title: "The Equalizer",
    video: false,
    vote_average: 7.242,
    vote_count: 7963,
  },
  {
    adult: false,
    backdrop_path: "/dGXKgxWmiPRZkxphtMvBuCEeLU0.jpg",
    genre_ids: [80, 35, 28, 12],
    id: 207703,
    original_language: "en",
    original_title: "Kingsman: The Secret Service",
    overview:
      "The story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius.",
    popularity: 59.362,
    poster_path: "/ay7xwXn1G9fzX9TUBlkGA584rGi.jpg",
    release_date: "2014-12-13",
    title: "Kingsman: The Secret Service",
    video: false,
    vote_average: 7.637,
    vote_count: 15537,
  },
  {
    adult: false,
    backdrop_path: "/g3hni0i9iAQ13jDGOFWavJFlojc.jpg",
    genre_ids: [28, 53],
    id: 341013,
    original_language: "en",
    original_title: "Atomic Blonde",
    overview:
      "An undercover MI6 agent is sent to Berlin during the Cold War to investigate the murder of a fellow agent and recover a missing list of double agents.",
    popularity: 19.613,
    poster_path: "/kV9R5h0Yct1kR8Hf8sJ1nX0Vz4x.jpg",
    release_date: "2017-07-26",
    title: "Atomic Blonde",
    video: false,
    vote_average: 6.405,
    vote_count: 5811,
  },
  {
    adult: false,
    backdrop_path: "/oVD3ClJBoomSQHtnJPAlMfes8YD.jpg",
    genre_ids: [28, 80],
    id: 339403,
    original_language: "en",
    original_title: "Baby Driver",
    overview:
      "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.",
    popularity: 45.237,
    poster_path: "/rmnQ9jKW72bHu8uKlMjPIb2VLMI.jpg",
    release_date: "2017-06-28",
    title: "Baby Driver",
    video: false,
    vote_average: 7.454,
    vote_count: 14510,
  },
  {
    adult: false,
    backdrop_path: "/r17jFHAemzcWPPtoO0UxjIX0xas.jpg",
    genre_ids: [28, 53, 80],
    id: 324552,
    original_language: "en",
    original_title: "John Wick: Chapter 2",
    overview:
      "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
    popularity: 76.088,
    poster_path: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
    release_date: "2017-02-08",
    title: "John Wick: Chapter 2",
    video: false,
    vote_average: 7.325,
    vote_count: 11855,
  },
  {
    adult: false,
    backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
    genre_ids: [28, 12, 878],
    id: 497698,
    original_language: "en",
    original_title: "Black Widow",
    overview:
      "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
    popularity: 73.593,
    poster_path: "/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg",
    release_date: "2021-07-07",
    title: "Black Widow",
    video: false,
    vote_average: 7.314,
    vote_count: 9167,
  },
  {
    adult: false,
    backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 226.885,
    poster_path: "/5weKu49pzJCt06OPpjvT80efnQj.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 7.992,
    vote_count: 18005,
  },
  {
    adult: false,
    backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
    genre_ids: [28, 12, 80],
    id: 385128,
    original_language: "en",
    original_title: "F9",
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 58.504,
    poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
    release_date: "2021-05-19",
    title: "F9",
    video: false,
    vote_average: 7.157,
    vote_count: 6558,
  },
  {
    adult: false,
    backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
    genre_ids: [28, 35, 12],
    id: 436969,
    original_language: "en",
    original_title: "The Suicide Squad",
    overview:
      "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
    popularity: 126.589,
    poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
    release_date: "2021-07-28",
    title: "The Suicide Squad",
    video: false,
    vote_average: 7.565,
    vote_count: 7557,
  },
];

export const ListMoviesComedy = [
  {
    adult: false,
    backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
    genre_ids: [28, 12, 35],
    id: 293660,
    original_language: "en",
    original_title: "Deadpool",
    overview:
      "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    popularity: 86.576,
    poster_path: "/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
    release_date: "2016-02-09",
    title: "Deadpool",
    video: false,
    vote_average: 7.606,
    vote_count: 28714,
  },
  {
    adult: false,
    backdrop_path: "/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg",
    genre_ids: [35],
    id: 18785,
    original_language: "en",
    original_title: "The Hangover",
    overview:
      "When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
    popularity: 80.505,
    poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
    release_date: "2009-06-02",
    title: "The Hangover",
    video: false,
    vote_average: 7.309,
    vote_count: 15674,
  },
  {
    adult: false,
    backdrop_path: "/giYuvpmpZbwkT3NtX4WdNYqGhxw.jpg",
    genre_ids: [35],
    id: 8363,
    original_language: "en",
    original_title: "Superbad",
    overview:
      "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    popularity: 54.23,
    poster_path: "/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    release_date: "2007-03-20",
    title: "Superbad",
    video: false,
    vote_average: 7.228,
    vote_count: 6534,
  },
  {
    adult: false,
    backdrop_path: "/5iHPV6M6aPKxXv3w8LTxsD6Zeot.jpg",
    genre_ids: [35],
    id: 8699,
    original_language: "en",
    original_title: "Anchorman: The Legend of Ron Burgundy",
    overview:
      "It's the 1970s and San Diego anchorman Ron Burgundy is the top dog in local TV, but that's all about to change when ambitious reporter Veronica Corningstone arrives as a new employee at his station.",
    popularity: 14.147,
    poster_path: "/Rdzsh3s6waplhSD7PUaBJovB7v.jpg",
    release_date: "2004-06-28",
    title: "Anchorman: The Legend of Ron Burgundy",
    video: false,
    vote_average: 6.721,
    vote_count: 3785,
  },
  {
    adult: false,
    backdrop_path: "/i7ITE05sYhXl5yBT7dW6ythLSBI.jpg",
    genre_ids: [35, 10749],
    id: 55721,
    original_language: "en",
    original_title: "Bridesmaids",
    overview:
      "Annie's life is a mess. But when she finds out her lifetime best friend is engaged, she simply must serve as Lillian's maid of honor. Though lovelorn and broke, Annie bluffs her way through the expensive and bizarre rituals. With one chance to get it perfect, she’ll show Lillian and her bridesmaids just how far you’ll go for someone you love.",
    popularity: 17.262,
    poster_path: "/gJtA7hYsBMQ7EM3sPBMUdBfU7a0.jpg",
    release_date: "2011-05-13",
    title: "Bridesmaids",
    video: false,
    vote_average: 6.527,
    vote_count: 4068,
  },
  {
    adult: false,
    backdrop_path: "/nImPkaVZrljYxkYrKGYwSZdf2XC.jpg",
    genre_ids: [35],
    id: 8467,
    original_language: "en",
    original_title: "Dumb and Dumber",
    overview:
      'Lloyd and Harry are two men whose stupidity is really indescribable. When Mary, a beautiful woman, loses an important suitcase with money before she leaves for Aspen, the two friends (who have found the suitcase) decide to return it to her. After some "adventures" they finally get to Aspen where, using the lost money they live it up and fight for Mary\'s heart.',
    popularity: 31.242,
    poster_path: "/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg",
    release_date: "1994-12-16",
    title: "Dumb and Dumber",
    video: false,
    vote_average: 6.601,
    vote_count: 5552,
  },
  {
    adult: false,
    backdrop_path: "/n53EPBWZiz69sYzNDZmamYHdo6Q.jpg",
    genre_ids: [35],
    id: 12133,
    original_language: "en",
    original_title: "Step Brothers",
    overview:
      "Brennan Huff and Dale Doback might be grown men. But that doesn't stop them from living at home and turning into jealous, competitive stepbrothers when their single parents marry. Brennan's constant competition with Dale strains his mom's marriage to Dale's dad, leaving everyone to wonder whether they'll ever see eye to eye.",
    popularity: 24.197,
    poster_path: "/jV0eDViuTRf9cmj4H0JNvbvaNbR.jpg",
    release_date: "2008-07-25",
    title: "Step Brothers",
    video: false,
    vote_average: 6.559,
    vote_count: 2817,
  },
  {
    adult: false,
    backdrop_path: "/zZoSxRhNwdqSBB5mVmRpXEwKFWv.jpg",
    genre_ids: [35, 10402, 10749],
    id: 114150,
    original_language: "en",
    original_title: "Pitch Perfect",
    overview:
      "College student Beca knows she does not want to be part of a clique, but that's exactly where she finds herself after arriving at her new school. Thrust in among mean gals, nice gals and just plain weird gals, Beca finds that the only thing they have in common is how well they sing together. She takes the women of the group out of their comfort zone of traditional arrangements and into a world of amazing harmonic combinations in a fight to the top of college music competitions.",
    popularity: 24.647,
    poster_path: "/ntRIoh8Qf1BI1AYGx0STfq0wUmb.jpg",
    release_date: "2012-09-28",
    title: "Pitch Perfect",
    video: false,
    vote_average: 7.297,
    vote_count: 6161,
  },
  {
    adult: false,
    backdrop_path: "/jrXKwUYxNLa7Dv7TPHToQ4mVmlF.jpg",
    genre_ids: [35],
    id: 8193,
    original_language: "en",
    original_title: "Napoleon Dynamite",
    overview:
      "A listless and alienated teenager decides to help his new friend win the class presidency in their small western high school, while he must deal with his bizarre family life back home.",
    popularity: 11.44,
    poster_path: "/g5PAKdu5aolXMnIRFkCo6vXq5Jh.jpg",
    release_date: "2004-06-11",
    title: "Napoleon Dynamite",
    video: false,
    vote_average: 6.785,
    vote_count: 1646,
  },
  {
    adult: false,
    backdrop_path: "/76aZQJSSQkcLF20Fx2wMrmnOZHJ.jpg",
    genre_ids: [35, 10749],
    id: 9522,
    original_language: "en",
    original_title: "Wedding Crashers",
    overview:
      "John and his buddy, Jeremy are emotional criminals who know how to use a woman's hopes and dreams for their own carnal gain. Their modus operandi: crashing weddings. Normally, they meet guests who want to toast the romantic day with a random hook-up. But when John meets Claire, he discovers what true love – and heartache – feels like.",
    popularity: 17.668,
    poster_path: "/lFM3lk2zVzC1YFnKm0r6LbFPyRu.jpg",
    release_date: "2005-07-13",
    title: "Wedding Crashers",
    video: false,
    vote_average: 6.47,
    vote_count: 4015,
  },
  {
    adult: false,
    backdrop_path: "/8uNx4YtClqB9duM4n6jOx8vWvvl.jpg",
    genre_ids: [35, 10749, 18],
    id: 4964,
    original_language: "en",
    original_title: "Knocked Up",
    overview:
      "A slacker and a career-driven woman accidentally conceive a child after a one-night stand. As they try to make the relationship work, they must navigate the challenges of parenthood and their differences in lifestyle and maturity.",
    popularity: 18.323,
    poster_path: "/b4OaXw2MW97VvIiZE0Sbn1NfxSh.jpg",
    release_date: "2007-06-01",
    title: "Knocked Up",
    video: false,
    vote_average: 6.268,
    vote_count: 3630,
  },
  {
    adult: false,
    backdrop_path: "/xfOB4nbbVMWC0F2v6AxwWH5BIOI.jpg",
    genre_ids: [35],
    id: 10625,
    original_language: "en",
    original_title: "Mean Girls",
    overview:
      "Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.",
    popularity: 58.655,
    poster_path: "/2ZkuQXvVhh45uSvkBej4S7Ix1NJ.jpg",
    release_date: "2004-04-30",
    title: "Mean Girls",
    video: false,
    vote_average: 7.185,
    vote_count: 7860,
  },
  {
    adult: false,
    backdrop_path: "/xHDynIimfsgj0ZOs0j5ma8v1vmM.jpg",
    genre_ids: [35, 18],
    id: 120467,
    original_language: "en",
    original_title: "The Grand Budapest Hotel",
    overview:
      "The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé. The story involves the theft and recovery of a priceless Renaissance painting, the battle for an enormous family fortune and the slow and then sudden upheavals that transformed Europe during the first half of the 20th century.",
    popularity: 32.202,
    poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    release_date: "2014-02-26",
    title: "The Grand Budapest Hotel",
    video: false,
    vote_average: 8.052,
    vote_count: 13629,
  },
  {
    adult: false,
    backdrop_path: "/n7EH9nyYzQfAD4j6599fFWuQxDG.jpg",
    genre_ids: [35],
    id: 9398,
    original_language: "en",
    original_title: "Zoolander",
    overview:
      "Clear the runway for Derek Zoolander, VH1's three-time male model of the year. His face falls when hippie-chic Hansel scooters in to steal this year's award. The evil fashion guru Mugatu seizes the opportunity to turn Derek into a killing machine. It's a well-designed conspiracy and only with the help of Hansel and a few well-chosen accessories like Matilda can Derek make the world safe for male models everywhere.",
    popularity: 24.952,
    poster_path: "/qdrbSneHZjJG2Dj0hhBxzzAo4HB.jpg",
    release_date: "2001-09-28",
    title: "Zoolander",
    video: false,
    vote_average: 6.202,
    vote_count: 4048,
  },
  {
    adult: false,
    backdrop_path: "/lU0v9ULZJ9A5145nLGUF8ZNZnPj.jpg",
    genre_ids: [35],
    id: 9377,
    original_language: "en",
    original_title: "Ferris Bueller's Day Off",
    overview:
      "After high school slacker Ferris Bueller successfully fakes an illness in order to skip school for the day, he goes on a series of adventures throughout Chicago with his girlfriend Sloane and best friend Cameron, all the while trying to outwit his wily school principal and fed-up sister.",
    popularity: 27.377,
    poster_path: "/9LTQNCvoLsKXP0LtaKAaYVtRaQL.jpg",
    release_date: "1986-06-11",
    title: "Ferris Bueller's Day Off",
    video: false,
    vote_average: 7.609,
    vote_count: 4417,
  },
  {
    adult: false,
    backdrop_path: "/3Wej7JW8Ikrzbm6h0lmSdeOYMmu.jpg",
    genre_ids: [35, 10749],
    id: 6957,
    original_language: "en",
    original_title: "The 40 Year Old Virgin",
    overview:
      "Andy Stitzer has a pleasant life with a nice apartment and a job stamping invoices at an electronics store. But at age 40, there's one thing Andy hasn't done, and it's really bothering his sex-obsessed male co-workers: Andy is still a virgin. Determined to help Andy get laid, the guys make it their mission to de-virginize him. But it all seems hopeless until Andy meets small business owner Trish, a single mom.",
    popularity: 27.991,
    poster_path: "/mVeoqL37gzhMXQVpONi9DGOQ3tZ.jpg",
    release_date: "2005-08-11",
    title: "The 40 Year Old Virgin",
    video: false,
    vote_average: 6.371,
    vote_count: 6147,
  },
  {
    adult: false,
    backdrop_path: "/sXfN4ir91SfTeoWidIukQWane43.jpg",
    genre_ids: [28, 35],
    id: 109414,
    original_language: "en",
    original_title: "This Is the End",
    overview:
      "While attending a party at James Franco's house, Seth Rogen, Jay Baruchel and many other celebrities are faced with the apocalypse.",
    popularity: 30.705,
    poster_path: "/7Wdc3etyBJA4432TYtz6n9GQd1c.jpg",
    release_date: "2013-06-12",
    title: "This Is the End",
    video: false,
    vote_average: 6.222,
    vote_count: 5882,
  },
  {
    adult: false,
    backdrop_path: "/tqSR6GOG2Hde0gwG3vO1Bw6TTo5.jpg",
    genre_ids: [35],
    id: 195589,
    original_language: "en",
    original_title: "Neighbors",
    overview:
      "A couple with a newborn baby face unexpected difficulties after they are forced to live next to a fraternity house.",
    popularity: 23.933,
    poster_path: "/dyO9BQ4M4flTOAzP79rmsz61yAT.jpg",
    release_date: "2014-05-08",
    title: "Neighbors",
    video: false,
    vote_average: 6.177,
    vote_count: 6529,
  },
  {
    adult: false,
    backdrop_path: "/wS9TiAS1WckeTS2IrFg5dRN9WQD.jpg",
    genre_ids: [35, 14],
    id: 72105,
    original_language: "en",
    original_title: "Ted",
    overview:
      "John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear or his girlfriend, Lori.",
    popularity: 42.716,
    poster_path: "/1QVZXQQHCEIj8lyUhdBYd2qOYtq.jpg",
    release_date: "2012-06-29",
    title: "Ted",
    video: false,
    vote_average: 6.402,
    vote_count: 11418,
  },
  {
    adult: false,
    backdrop_path: "/ysUbm8qcKLaUiMf0H82mE5ujvVQ.jpg",
    genre_ids: [27, 35],
    id: 747,
    original_language: "en",
    original_title: "Shaun of the Dead",
    overview:
      "Shaun lives a supremely uneventful life, which revolves around his girlfriend, his mother, and, above all, his local pub. This gentle routine is threatened when the dead return to life and make strenuous attempts to snack on ordinary Londoners.",
    popularity: 27.923,
    poster_path: "/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg",
    release_date: "2004-04-09",
    title: "Shaun of the Dead",
    video: false,
    vote_average: 7.539,
    vote_count: 7667,
  },
  {
    adult: false,
    backdrop_path: "/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg",
    genre_ids: [80, 18, 35],
    id: 106646,
    original_language: "en",
    original_title: "The Wolf of Wall Street",
    overview:
      "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
    popularity: 95.747,
    poster_path: "/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
    release_date: "2013-12-25",
    title: "The Wolf of Wall Street",
    video: false,
    vote_average: 8.037,
    vote_count: 21990,
  },
  {
    adult: false,
    backdrop_path: "/oLp6ueqQXNWvWCFwrb6tXDnH0Ye.jpg",
    genre_ids: [35, 80, 28],
    id: 290250,
    original_language: "en",
    original_title: "The Nice Guys",
    overview:
      "A private eye investigates the apparent suicide of a fading porn star in 1970s Los Angeles and uncovers a conspiracy.",
    popularity: 25.144,
    poster_path: "/clq4So9spa9cXk3MZy2iMdqkxP2.jpg",
    release_date: "2016-05-15",
    title: "The Nice Guys",
    video: false,
    vote_average: 7.109,
    vote_count: 7145,
  },
  {
    adult: false,
    backdrop_path: "/7tTCnQcKzUkabDV3BJMe7LIzlEs.jpg",
    genre_ids: [35, 18, 10749],
    id: 455207,
    original_language: "en",
    original_title: "Crazy Rich Asians",
    overview:
      "An American-born Chinese economics professor accompanies her boyfriend to Singapore for his best friend's wedding, only to get thrust into the lives of Asia's rich and famous.",
    popularity: 20.131,
    poster_path: "/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg",
    release_date: "2018-08-15",
    title: "Crazy Rich Asians",
    video: false,
    vote_average: 7.075,
    vote_count: 3334,
  },
  {
    adult: false,
    backdrop_path: "/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg",
    genre_ids: [16, 12, 10751, 35],
    id: 862,
    original_language: "en",
    original_title: "Toy Story",
    overview:
      "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
    popularity: 101.025,
    poster_path: "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    release_date: "1995-10-30",
    title: "Toy Story",
    video: false,
    vote_average: 7.968,
    vote_count: 16992,
  },
  {
    adult: false,
    backdrop_path: "/ti6kJ80ZB8RZTiDIzPkhaCJMoqq.jpg",
    genre_ids: [35, 80],
    id: 115,
    original_language: "en",
    original_title: "The Big Lebowski",
    overview:
      "Jeffrey 'The Dude' Lebowski, a Los Angeles slacker who only wants to bowl and drink White Russians, is mistaken for another Jeffrey Lebowski, a wheelchair-bound millionaire, and finds himself dragged into a strange series of events involving nihilists, adult film producers, ferrets, errant toes, and large sums of money.",
    popularity: 27.316,
    poster_path: "/97Ryzu1OXNvb36dxSt5tmz4EKEC.jpg",
    release_date: "1998-03-06",
    title: "The Big Lebowski",
    video: false,
    vote_average: 7.841,
    vote_count: 10275,
  },
  {
    adult: false,
    backdrop_path: "/a7DCwfYAiIN15qfmFmrLcHh751E.jpg",
    genre_ids: [28, 35, 12, 10752],
    id: 7446,
    original_language: "en",
    original_title: "Tropic Thunder",
    overview:
      "Ben Stiller, Jack Black and Robert Downey Jr. lead an ensemble cast in 'Tropic Thunder,' an action comedy about a group of self-absorbed actors who set out to make the most expensive war film. After ballooning costs force the studio to cancel the movie, the frustrated director refuses to stop shooting, leading his cast into the jungles of Southeast Asia, where they encounter real bad guys.",
    popularity: 23.991,
    poster_path: "/zAurB9mNxfYRoVrVjAJJwGV3sPg.jpg",
    release_date: "2008-08-09",
    title: "Tropic Thunder",
    video: false,
    vote_average: 6.629,
    vote_count: 5519,
  },
  {
    adult: false,
    backdrop_path: "/aO6Z7ErkEoahGFKYdEs4k4ilWFe.jpg",
    genre_ids: [28, 35, 80],
    id: 10189,
    original_language: "en",
    original_title: "Pineapple Express",
    overview:
      "A stoner and his dealer are forced to go on the run from the police after the pothead witnesses a cop commit a murder.",
    popularity: 22.252,
    poster_path: "/6E50WjeOYjDZg9HXgPjYdGtY2jG.jpg",
    release_date: "2008-08-06",
    title: "Pineapple Express",
    video: false,
    vote_average: 6.62,
    vote_count: 3434,
  },
  {
    adult: false,
    backdrop_path: "/zJDMuXQDraHjtF53wikmyBQIcYe.jpg",
    genre_ids: [12, 28, 35, 14],
    id: 353486,
    original_language: "en",
    original_title: "Jumanji: Welcome to the Jungle",
    overview:
      "Four teenagers in detention discover an old video game console with a game they’ve never heard of. When they decide to play, they are immediately sucked into the jungle world of Jumanji in the bodies of their avatars. They’ll have to complete the adventure of their lives filled with fun, thrills and danger or be stuck in the game forever!",
    popularity: 33.941,
    poster_path: "/pSgXKPU5h6U89ipF7HBYajvYt7j.jpg",
    release_date: "2017-12-09",
    title: "Jumanji: Welcome to the Jungle",
    video: false,
    vote_average: 6.825,
    vote_count: 12688,
  },
  {
    adult: false,
    backdrop_path: "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg",
    genre_ids: [28, 35, 12],
    id: 383498,
    original_language: "en",
    original_title: "Deadpool 2",
    overview:
      "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
    popularity: 74.475,
    poster_path: "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    release_date: "2018-05-10",
    title: "Deadpool 2",
    video: false,
    vote_average: 7.492,
    vote_count: 16194,
  },
  {
    adult: false,
    backdrop_path: "/agoBZfL1q5G79SD0npArSlJn8BH.jpg",
    genre_ids: [35, 10752, 18],
    id: 515001,
    original_language: "en",
    original_title: "Jojo Rabbit",
    overview:
      "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
    popularity: 28.121,
    poster_path: "/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
    release_date: "2019-10-18",
    title: "Jojo Rabbit",
    video: false,
    vote_average: 8.046,
    vote_count: 8620,
  },
];

export const AllGenres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];
